# Generated by Django 5.2.5 on 2025-09-20 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(verbose_name='URL da rede social')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link de rede social',
                'verbose_name_plural': 'Links de redes sociais',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='redes_sociais',
            field=models.ManyToManyField(blank=True, to='users.usersociallink'),
        ),
    ]
