# Generated by Django 5.2.5 on 2025-09-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersociallink_profile_redes_sociais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='redes_sociais',
        ),
    ]
