# Generated by Django 5.2.5 on 2025-09-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True),
        ),
    ]
