# Generated by Django 5.2.5 on 2025-09-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vinculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
