# Generated by Django 5.2.5 on 2025-09-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_usual',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
