# Generated by Django 5.2.5 on 2025-09-21 17:12

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IdentidadeVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('cor_sistema', models.CharField(default='#005EFF', max_length=7)),
                ('cor_suplente', models.CharField(blank=True, max_length=7, null=True)),
                ('cor_titulo', models.CharField(default='#FF9823', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('nome', models.CharField(max_length=150)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('url_base', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('conteudo', tinymce.models.HTMLField(blank=True, verbose_name='Conteúdo')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('area_conhecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_conhecimento_noticia', to='repex.areaconhecimento')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('resumo', tinymce.models.HTMLField(blank=True, verbose_name='Resumo')),
                ('justificativa', tinymce.models.HTMLField(blank=True, verbose_name='Justificativa')),
                ('objetivo', tinymce.models.HTMLField(blank=True, verbose_name='Objetivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resultados', tinymce.models.HTMLField(blank=True, verbose_name='Resultados')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='media/')),
                ('palavras_chave', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], max_length=20)),
                ('modalidade', models.CharField(choices=[('Ensino', 'Ensino'), ('Pesquisa', 'Pesquisa'), ('Extensão', 'Extensão')], max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('area_conhecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_conhecimento', to='repex.areaconhecimento')),
                ('componentes', models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='repex.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='UserSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL da rede social')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repex.redesocial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link de rede social',
                'verbose_name_plural': 'Links de redes sociais',
            },
        ),
    ]
