# Generated by Django 5.1.7 on 2025-08-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('conteudo', models.TextField(max_length=3000)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('area_conhecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_conhecimento_noticia', to='repex.areaconhecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField(max_length=3000)),
                ('justificativa', models.TextField(max_length=2000)),
                ('objetivo', models.TextField(max_length=2000)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('resultados', models.TextField(max_length=3000)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
                ('palavras_chave', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], max_length=20)),
                ('modalidade', models.CharField(choices=[('Ensino', 'Ensino'), ('Pesquisa', 'Pesquisa'), ('Extensão', 'Extensão')], max_length=20)),
                ('area_conhecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_conhecimento', to='repex.areaconhecimento')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='repex.projeto')),
            ],
        ),
    ]
