# Generated by Django 5.2.5 on 2025-08-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.TextField(max_length=2000)),
                ('objetivo', models.TextField(max_length=2000)),
                ('capa', models.ImageField(upload_to='', verbose_name='media/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('palavras_chave', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='repex.projeto')),
            ],
        ),
    ]
