# Generated by Django 5.2.5 on 2025-09-28 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='area_conhecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_conhecimento', to='repex.areaconhecimento'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='projetos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fotoprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='repex.projeto'),
        ),
        migrations.AddField(
            model_name='usersociallink',
            name='rede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rede', to='repex.redesocial'),
        ),
        migrations.AddField(
            model_name='usersociallink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
