# Generated by Django 5.2.5 on 2025-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
