# Generated by Django 5.2.5 on 2025-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersociallink',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
