# Generated by Django 5.2.5 on 2025-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='componentes', to='users.profile'),
        ),
    ]
