# Generated by Django 5.2.5 on 2025-09-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0002_alter_usersociallink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersociallink',
            name='rede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rede', to='repex.redesocial'),
        ),
    ]
