# Generated by Django 5.1.7 on 2025-08-19 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0002_projeto_componentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='componentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
