# Generated by Django 5.2.5 on 2025-09-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('nome', models.CharField(max_length=150)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
