# Generated by Django 5.2.5 on 2025-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='colab',
            field=models.ManyToManyField(blank=True, related_name='colaboradores', to='repex.projeto'),
        ),
    ]
