# Generated by Django 5.2.5 on 2025-09-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0002_projeto_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialLink',
        ),
    ]
