# Generated by Django 5.2.5 on 2025-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0003_projeto_colab'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidadevisual',
            name='frase',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
