# Generated by Django 5.2.5 on 2025-09-15 21:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0003_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identidadevisual',
            name='cor_sistema',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='identidadevisual',
            name='cor_suplente',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='identidadevisual',
            name='cor_titulo',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
