# Generated by Django 5.2.5 on 2025-09-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0003_alter_usersociallink_rede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redesocial',
            name='icone',
        ),
    ]
