# Generated by Django 5.2.5 on 2025-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0004_identidadevisual_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identidadevisual',
            name='frase',
            field=models.CharField(default='Repositório IFSPP, aqui é o lar de todos os nossos projetos!', max_length=300),
        ),
    ]
