# Generated by Django 5.2.5 on 2025-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0005_alter_identidadevisual_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identidadevisual',
            name='frase',
            field=models.CharField(max_length=300),
        ),
    ]
