# Generated by Django 5.2.5 on 2025-08-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0005_alter_projeto_componentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('url_base', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
