# Generated by Django 5.2.5 on 2025-10-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0006_alter_identidadevisual_frase'),
    ]

    operations = [
        migrations.AddField(
            model_name='identidadevisual',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='identidadevisual',
            name='frase',
            field=models.CharField(default='Repositório IFSPP, aqui é o lar de todos os nossos projetos!', max_length=300),
        ),
    ]
