# Generated by Django 5.2.5 on 2025-08-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0006_redessociais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedesSociais',
            new_name='RedeSocial',
        ),
    ]
