# Generated by Django 5.2.5 on 2025-10-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0007_identidadevisual_img_alter_identidadevisual_frase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identidadevisual',
            old_name='img',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='identidadevisual',
            old_name='frase',
            new_name='pagina_inicial_frase',
        ),
    ]
