# Generated by Django 5.2.5 on 2025-10-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0008_rename_img_identidadevisual_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Proposta', 'Proposta'), ('Em andamento', 'Em andamento'), ('Pausado', 'Pausado'), ('Concluído', 'Concluído')], max_length=20),
        ),
    ]
