# Generated by Django 5.2.5 on 2025-08-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0008_usersociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('cor_sistema', models.CharField(default='#005EFF', max_length=7)),
                ('cor_suplente', models.CharField(blank=True, max_length=7, null=True)),
                ('cor_titulos', models.CharField(default='#FF9823', max_length=7)),
            ],
        ),
    ]
