# Generated by Django 5.2.5 on 2025-08-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0009_identidadevisual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identidadevisual',
            old_name='cor_titulos',
            new_name='cor_titulo',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
