# Generated by Django 5.2.5 on 2025-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0009_alter_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='modalidade',
            field=models.CharField(choices=[('Ensino', 'Ensino'), ('Pesquisa', 'Pesquisa'), ('Extensão', 'Extensão'), ('Interdisciplinar', 'Interdisciplinar')], max_length=20),
        ),
    ]
