# Generated by Django 5.2.5 on 2025-09-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0010_rename_cor_titulos_identidadevisual_cor_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoprojeto',
            old_name='photo',
            new_name='foto',
        ),
    ]
