# Generated by Django 5.2.5 on 2025-09-14 00:57

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0011_rename_photo_fotoprojeto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Conteúdo'),
        ),
    ]
