# Generated by Django 5.2.5 on 2025-09-14 01:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0012_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='justificativa',
            field=tinymce.models.HTMLField(verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='objetivo',
            field=tinymce.models.HTMLField(verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resultados',
            field=tinymce.models.HTMLField(verbose_name='Resultados'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=tinymce.models.HTMLField(verbose_name='Resumo'),
        ),
    ]
