# Generated by Django 5.2.5 on 2025-09-14 01:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0013_alter_projeto_justificativa_alter_projeto_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='justificativa',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='objetivo',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resultados',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Resultados'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Resumo'),
        ),
    ]
